# Generated by Django 5.1.2 on 2024-10-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_log_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dob',
            field=models.CharField(default='08/06/2005', max_length=255),
            preserve_default=False,
        ),
    ]
